Using ``pytest.raises`` or ``unittest.TestCase.assertRaises`` will assert that an exception is raised in the following block. Ending such block in an assertion means that the test can succeed with that last assertion never being executed.
